// This file was automatically generated by the `generateJDiffJs` Gradle task. Do not manually edit.
angular.module('Index', [])
  .controller('JDiff', ['$scope', function ($scope) {
    $scope['j-diff-reports'] = [
        '1.11.0-to-1.12.11',
        '1.11.0-to-1.12.10'].map(function (jDiffReport) {
          return [jDiffReport.replace(/.*-to-/, ''), jDiffReport];
        });
  }]);